name: 'Ed Madison '
favicon: null
layout_spectrum: 0.20844634878449142
typography_spectrum: 0.8696128383744508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2294641467742622
  lightness: 0.1955635545309633
  saturation: 0.4704758543521166
  rhythmicContrast: 0.030377847841009498
purpose: []
